CREATE TABLE IF NOT EXISTS saves (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(80) NOT NULL,
  author VARCHAR(40) NOT NULL,
  description VARCHAR(280) NOT NULL DEFAULT '',
  filename VARCHAR(120) NOT NULL,
  size_bytes INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  downloads INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
